services:
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=dance-store;Username=postgres;Password=12345
      - ASPNETCORE_URLS=http://+:80

  db:
    image: postgres:15
    container_name: postgres-db-dance-store
    restart: always
    environment:
      - POSTGRES_DB=dance-store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "1818:5432"
    volumes:
      - dance-store:/var/lib/postgresql/data

volumes:
  dance-store: