services:
  db:
    image: postgres:15
    container_name: postgres-db-dance-store
    restart: always
    environment:
      - POSTGRES_DB=dance-store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "1818:5432"
    volumes:
      - dance-store:/var/lib/postgresql/data

volumes:
  dance-store: