// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductApp.Data;

#nullable disable

namespace ProductApp.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250312091406_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductApp.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Care")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Care = "Ручная стирка",
                            Color = "Черный",
                            Description = "Элегантное боди Caero для бальных танцев.",
                            Gender = "Женский",
                            Image = "/img/catalog/bodi_caero.jpg",
                            Length = 100.0,
                            Material = "Хлопок",
                            Name = "Боди Caero",
                            Price = 1500m,
                            Season = "Лето",
                            Size = "M",
                            Type = "Боди"
                        },
                        new
                        {
                            Id = 2,
                            Care = "Ручная стирка",
                            Color = "Белый",
                            Description = "Элегантное боди Volano для танцев.",
                            Gender = "Женский",
                            Image = "/img/catalog/bodi_volano.jpg",
                            Length = 100.0,
                            Material = "Шелк",
                            Name = "Боди Volano",
                            Price = 1600m,
                            Season = "Лето",
                            Size = "M",
                            Type = "Боди"
                        },
                        new
                        {
                            Id = 3,
                            Care = "Химчистка",
                            Color = "Синий",
                            Description = "Стильные брюки Frandio для мужчин.",
                            Gender = "Мужской",
                            Image = "/img/catalog/bruki_muzsk.jpg",
                            Length = 110.0,
                            Material = "Лён",
                            Name = "Брюки Frandio",
                            Price = 2000m,
                            Season = "Осень",
                            Size = "L",
                            Type = "Брюки"
                        },
                        new
                        {
                            Id = 4,
                            Care = "Полировка",
                            Color = "Черные",
                            Description = "Классические мужские туфли.",
                            Gender = "Мужской",
                            Image = "/img/catalog/muzhskie_tufli.jpg",
                            Length = 30.0,
                            Material = "Кожа",
                            Name = "Мужские туфли",
                            Price = 2300m,
                            Season = "Зима",
                            Size = "42",
                            Type = "Туфли"
                        },
                        new
                        {
                            Id = 5,
                            Care = "Ручная стирка",
                            Color = "Бежевый",
                            Description = "Элегантное платье для бальных танцев.",
                            Gender = "Женский",
                            Image = "/img/catalog/plate_clarine_beige.jpg",
                            Length = 140.0,
                            Material = "Шелк и эластан",
                            Name = "Платье Clarine Beige",
                            Price = 3000m,
                            Season = "Весна/Лето",
                            Size = "38",
                            Type = "Платье"
                        },
                        new
                        {
                            Id = 6,
                            Care = "Химчистка",
                            Color = "Розовый",
                            Description = "Платье Clarine Rustica Roze в элегантном стиле.",
                            Gender = "Женский",
                            Image = "/img/catalog/plate_clarine_rustica_roze.jpg",
                            Length = 135.0,
                            Material = "Шелк",
                            Name = "Платье Clarine Rustica Roze",
                            Price = 3200m,
                            Season = "Осень",
                            Size = "40",
                            Type = "Платье"
                        },
                        new
                        {
                            Id = 7,
                            Care = "Ручная стирка",
                            Color = "Красный",
                            Description = "Яркое платье Fuego Ardiente Red для смелых образов.",
                            Gender = "Женский",
                            Image = "/img/catalog/plate_fuego_ardiente_red.jpg",
                            Length = 130.0,
                            Material = "Шелк",
                            Name = "Платье Fuego Ardiente Red",
                            Price = 3500m,
                            Season = "Лето",
                            Size = "36",
                            Type = "Платье"
                        },
                        new
                        {
                            Id = 8,
                            Care = "Стирка в машине",
                            Color = "Белый",
                            Description = "Стильная рубашка Frame для мужчин.",
                            Gender = "Мужской",
                            Image = "/img/catalog/rubashka_frame.jpg",
                            Length = 70.0,
                            Material = "Хлопок",
                            Name = "Рубашка Frame",
                            Price = 1800m,
                            Season = "Весна",
                            Size = "M",
                            Type = "Рубашка"
                        },
                        new
                        {
                            Id = 9,
                            Care = "Полировка",
                            Color = "Бежевый",
                            Description = "Изящные женские туфли для стильного образа.",
                            Gender = "Женский",
                            Image = "/img/catalog/tufli_latina_zhensk.jpg",
                            Length = 25.0,
                            Material = "Кожа",
                            Name = "Женские туфли",
                            Price = 2800m,
                            Season = "Лето",
                            Size = "37",
                            Type = "Туфли"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
